---
- name: Converge
  hosts: all
  vars:
    qbittorrent_nox_webui_port: 18080
  tasks:
    - name: "Include sagikazarmark.qbittorrent_nox"
      include_role:
        name: "sagikazarmark.qbittorrent_nox"
