name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "30 5 * * 2"

defaults:
  run:
    working-directory: sagikazarmark.qbittorrent_nox

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: sagikazarmark.qbittorrent_nox

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Lint
        run: molecule lint

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian10
          - debian9
          - ubuntu1804
          - ubuntu2004

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: sagikazarmark.qbittorrent_nox

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Test
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
